plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - "prettier-plugin-tailwindcss"
importOrder:
  ["^react(.*)", "next/(.*)", "<THIRD_PARTY_MODULES>", "@/(.*)", "^[./]"]
importOrderSortSpecifiers: true
