name: 👮‍♂️ Sanity checks

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  prettify-n-lint:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
          run_install: |
            - args: [--prefer-offline, --frozen-lockfile]

      - name: Prettier and lint
        run: |
          pnpm lint:check
          pnpm lint:check:interface

  codespell:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run codespell
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2.0
        with:
          check_filenames: true
          skip: ./.git,pnpm-lock.yaml
          ignore_words_list: superseed

  validate-links:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby_version:
          - 4.0

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Install awesome_bot
        run: gem install awesome_bot -v 1.20.0

      - name: Validate URLs
        run: |
          awesome_bot ./*.md src/*.sol test/**/*.sol test/public/**/*.sol interface/*.md interface/public/*.css interface/src/**/*.css interface/src/**/*.tsx interface/src/**/*.ts interface/src/components/**/*.tsx deployments/*.json \
          --allow-dupe --request-delay 0.4 \
          --white-list "https://github.com/pcaversaccio/createx/issues/new?assignees=pcaversaccio&labels=new+deployment+%E2%9E%95&projects=&template=deployment_request.yml&title=%5BNew-Deployment-Request%5D%3A+",https://foundry.paradigm.xyz,https://github.com/pcaversaccio/createx.git,https://x.com,https://dune.com
